In [ ]:
# ===========================================
# ML Theory Notebook - Day A
# Week 1 (11th Sept 2025)
# Topic: Vectors, Dot Product, Matrix Multiplication
# ===========================================

# --- Section 1: Definitions ---
# Definitions:
# - Vector - a quantity with multiple direction components
# - Dot product - operation that takes two same-dimension vectors and sums of the multiples of the corresponding components, resulting in a scalar quantity
# - Matrix multiplication - a process of multiplying two matrices. For example, A x B = AB, but B x A = BA and it is not the same as AB, where A,B are matrices
# - Associativity - a term used in mathematics to describe that grouping does not change the result i.e. A(BC) = (AB)C
# - Distributivity - a term in mathematics that describes that a factor multiplied by the sum of two terms is equivalent of this factor multiplied by each term individually

In [8]:
import numpy as np

In [ ]:
### --- Section 2: Quick Calc ---

In [5]:
# Example 1: Dot product
v1 = np.array([1,2])
v2 = np.array([3,4])
print(np.dot(v1,v2))

11


In [15]:
# Example 2: Matrix multiplication
A = np.array( [[1, 2],
              [3, 4]] )
B = np.array( [[3, 2],
              [1, 1]] )
print("AB = \n",np.dot(A,B))

AB = 
 [[ 5  4]
 [13 10]]


In [16]:
#Example 3: Show AB ≠ BA
AB = np.dot(A,B)
BA = np.dot(B,A)
print("AB = \n",AB)
print("BA = \n",BA)

AB = 
 [[ 5  4]
 [13 10]]
BA = 
 [[ 9 14]
 [ 4  6]]


In [ ]:
### --- Section 3: Derivation Exercise ---

In [19]:
# Prove distributive law: A(B + C) = AB + AC
#Keeping A and B the same throughout
C = np.array( [[5,2],
               [1,3]] )
s1 = np.dot(A, B+C)
s2 = np.dot(A, B) + np.dot(A, C)
print(s1)
print(s2)
print(np.allclose(s1,s2))
#s1 == s2

[[12 12]
 [32 28]]
[[12 12]
 [32 28]]
True


In [ ]:
### --- Section 4: Reflections ---

In [ ]:
# - 5 bullet points: what you learned
#1. A product of matrix with vector is linear combination of vector's features
#2. Elimination algorithm allows to find n roots of the n-variable simultaneous equations
#3. The problem of combinations method is when all the vectors lie in the same plane
#4. Any equation can be writtes as Ax = b, where A is matrix of coefficients, x is vector of features, b is vector of results
#5. If any column of linear combination in n-dimensional space happens to be the same one as any other column in the same system, then it will fill a (n-1)th dimensional "hyperplain" in n-dimensional space
# - 2 confusing points
#1. How do you know when to apply a row exchange in case you spot a failure solving the simultaneous equations with elimination method?
#2. Suppose there are perpendicular vectors in a linear combination. Would this in any way affect the calculation, or does it only relate to parallel vectors?